#数据源配置
spring:
  main:
    # 允许循环依赖
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 解决前端传递过来的参数不能转成LocalDateTime
  redis:
    host: ip
    port: 6379
    timeout: 1000
    password: password
    jedis:
      pool:
        max-active: 10 # 最大链接数
        min-idle: 5 # 最小核心线程
        max-idle: 10 # 最大线程
        max-wait: 2000 # 最大等待时间2S
  profiles:
    include: mqtt, mysql-mult, es #用英文逗号分割如有多个


#mybatis 相关配置
mybatis:
  type-aliases-package: com.fun.uncle.springboot2020.domain
  mapper-locations: classpath:mapper/**/*.xml # **表示任意目录 *表示任意文件

# 打印指定的目录下的mysql语句，建议使用这个
#logging:
#  level:
#    com.fun.uncle.springboot2020.mapper: DEBUG
      # 输出 SQL
#    druid.sql.Statement: debug
      # 输出查询结果
#    druid.sql.ResultSet: debug


## obs 相关配置 ##
obs:
  endPoint: #endpoint#
  ak: #永久的AK#
  sk: #永久的SK#
  bucketName: #自己的bucket#

aliyun:
  oss:
    accessKey:
    secret:
    roleArn: acs:ram::1722036088967776:role/aliyunosstokengeneratorrole
    roleSessionName: external-username
    endpoint:
    bucketName:
    privateBucketName: