## MQTT##
mqtt:
  username: username
  password: password
  host-url: tcp://ip:11883
  in-client-id: summerIn${random.value}        # 随机值，使出入站 client ID 不同
  out-client-id: summerOut${random.value}
  client-id: ${random.int}                   # 客户端Id，不能相同，采用随机数 ${random.value}
  timeout: 60                                # 超时时间
  keepalive: 60                              # 保持连接
  clearSession: true                         # 清除会话(设置为false,断开连接，重连后使用原来的会话 保留订阅的主题，能接收离线期间的消息)
  subscribe-topics:                                 # 订阅的topic
    - dev/a/#
    - dev/b/#
    - dev/c/#
  handle-topic:
    t1MessageHandle: dev/a
    t2MessageHandle: dev/b