#数据源配置
spring:
  datasource:
    url: jdbc:mysql://www.fununcle.top:3306/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ruan123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

#mybatis 相关配置
mybatis:
  type-aliases-package: com.fun.uncle.springboot2020.domain
  mapper-locations: classpath:mapper/*.xml

