#数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://www.fununcle.top:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: Ruan@U66ZaNXesKCy8J95epObxSvlvgyWHdWT
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      # 申请连接时执行validationQuery检测连接是否有效
      testOnBorrow: false
      # 归还连接时执行validationQuery检测连接是否有效
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      # poolPreparedStatements: true
      # maxPoolPreparedStatementPerConnectionSize: 20
      stat-view-servlet: ## 开启监控
        # 开启监控页面
        enabled: true
        # 监控系统用户名
        login-username: druid
        # 监控系统密码
        login-password: 123456
        # 是否允许清空监控数据
        reset-enable: false
        # 监控系统路径
        url-pattern: "/druid/*"
        # 可访问监控系统的 IP 列表（白名单）
        # allow: 127.0.0.1
        # 禁止访问监控系统的 IP 列表（黑名单）
        # deny:
      # 配置扩展插件，常用的插件有：监控统计用的 stat，日志用的 slf4j，防御 sql 注入的 wall
      filters: stat,wall,slf4j
      # 用来打开 SQL 参数化合并监控和慢 SQL 记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个 DruidDataSource 的监控数据
      useGlobalDataSourceStat: true
        # 开启 web 监控（Web应用、URI监控、Session监控）
      web-stat-filter:
        # 开启 Web 监控
        enabled: true
        # 需要监控的路径
        url-pattern: /*
        # 不监控静态文件和监控系统自己的请求
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        # 统计请求调用链
        profile-enable: true
      # 开启 Spring 监控
      aop-patterns: com.fun.uncle.springboot2020.controller.*,com.fun.uncle.springboot2020.service.*,com.fun.uncle.springboot2020.mapper.*
        # 日志配置
      filter:
        slf4j:
          enabled: true
          statement-executable-sql-log-enable: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 解决前端传递过来的参数不能转成LocalDateTime
  redis:
    host: www.fununcle.top
    port: 6379
    timeout: 1000
    password: 8d^5t2xaHA2BaOZe$$6h!K*PqkgnJ8kxBCd3XMFjo&STNIDTEC3uuGfH9j8YNsZ#
    jedis:
      pool:
        max-active: 10 # 最大链接数
        min-idle: 5 # 最小核心线程
        max-idle: 10 # 最大线程
        max-wait: 2000 # 最大等待时间2S


#mybatis 相关配置
mybatis:
  type-aliases-package: com.fun.uncle.springboot2020.domain
  mapper-locations: classpath:mapper/**/*.xml # **表示任意目录 *表示任意文件

# 打印指定的目录下的mysql语句，建议使用这个
#logging:
#  level:
#    com.fun.uncle.springboot2020.mapper: DEBUG
      # 输出 SQL
#    druid.sql.Statement: debug
      # 输出查询结果
#    druid.sql.ResultSet: debug

## MQTT##
mqtt:
  username:
  password:
  host-url: tcp://ip:11883
#  in-client-id: ${random.value}         # 随机值，使出入站 client ID 不同
  in-client-id: summerIn${random.value}        # 随机值，使出入站 client ID 不同
  out-client-id: summerOut${random.value}
  client-id: ${random.int}                   # 客户端Id，不能相同，采用随机数 ${random.value}
  default-topic: $share/testTaskGroup/test/skipRope/dataUp/#, $share/testTaskGroup/client/event       # 默认主题
  timeout: 60                                # 超时时间
  keepalive: 60                              # 保持连接
  clearSession: true                         # 清除会话(设置为false,断开连接，重连后使用原来的会话 保留订阅的主题，能接收离线期间的消息)

## obs 相关配置 ##
obs:
  endPoint: #endpoint#
  ak: #永久的AK#
  sk: #永久的SK#
  bucketName: #自己的bucket#