#数据源配置
spring:
  datasource:
    url: jdbc:mysql://www.fununcle.top:3306/springboot?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ruan123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: www.fununcle.top
    port: 6379
    timeout: 1000

    password: 123456
    jedis:
      pool:
        max-active: 10 # 最大链接数
        min-idle: 5 # 最小核心线程
        max-idle: 10 # 最大线程
        max-wait: 2000 # 最大等待时间2S


#mybatis 相关配置
mybatis:
  type-aliases-package: com.fun.uncle.springboot2020.domain
  mapper-locations: classpath:mapper/*.xml

# 打印指定的目录下的mysql语句，建议使用这个
logging:
  level:
    com.fun.uncle.springboot2020.mapper: DEBUG

